/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Network */

#ifndef _Included_Network
#define _Included_Network
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Network
 * Method:    modWeights
 * Signature: ([LPerceptron;[F)V
 */
JNIEXPORT void JNICALL Java_Network_modWeights
  (JNIEnv *, jclass, jobjectArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
